schedules:
- cron: "41 * * * *"
  displayName: Testing 2 cron
  branches: 
    include:
      - master
  always: true

trigger: none

pool: 'Default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
