schedules:
- cron: "4 * * * *"
  displayName: Testing 2 cron
  branches: 
    include:
      - master
  always: true

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
